version: '3.9'

services:
  rethinkdb:
    image: rethinkdb:latest
    ports:
     - 28015:28015
     - 29015:29015
     - 8080:8080
    volumes:
     - ~/apps/rethinkdb:/data
    command: rethinkdb --bind all
  postgres:
    image: postgres:latest
    ports:
      - 5432:5432
    volumes:
      - ~/apps/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
    restart: always